---
- hosts: all
  tasks:
          - name: Install Pkgs for apt over HTTPS
            apt :
                    name: "{{ packages }}"
                    state: present
                    update_cache: yes
            vars :
                    packages:
                            - apt-transport-https
                            - ca-certificates
                            - curl
                            - gnupg-agent
                            - software-properties-common

          - name: Add apt signing key for docker
            apt_key :
                    url : https://download.docker.com/linux/ubuntu/gpg
                    state : present 

          - name: Add apt repository for stable version
            apt_repository :
                    repo : deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
                    state : present 

          - name: Install docker and its dependancies
            apt :
                    name: "{{ packages }}"
                    state: present
                    update_cache: yes
            vars :
                    packages:
                            - docker-ce
                            - docker-ce-cli
                            - containerd.io
                    notify:
                            - Docker status

          - name: Add cloud_user to docker group
            user :
                    name: cloud_user
                    groups : docker
                    append : yes
            tags :
                    - add_user_to_docker

          - name: Remove swapfile from /etc/fstab
            mount :
                    name : "{{ item }}"
                    fstype: swap
                    state : absent
            with_items:
                    - swap
                    - none

          - name: Disable swap
            command : swapoff -a
            when : ansible_swaptotal_mb > 0

          - name: Add apt signing key for Kubernetes
            apt_key :
                    url : https://packages.cloud.google.com/apt/doc/apt-key.gpg
                    state : present

          - name: Add apt repositoriesfor Kubernetes
            apt_repository:
                    repo : deb https://apt.kubernetes.io/ kubernetes-xenial main
                    state : present
                    filename: kubernetes.list

          - name: Install k8s binaries
            apt :
                    name: "{{ packages }}"
                    state : present
                    update_cache : yes
            vars:
                    packages:
                             - kubelet
                             - kubeadm
                             - kubectl

          - name: Restart kubelet
            service:
                    name: kubelet
                    daemon_reload : yes
                    state: restarted

          - name: Copy join command to server location
            copy: 
                src : /home/cloud_user/join-command 
                dest : /tmp/join_command.sh 
                mode : 0777
                owner : cloud_user
                group : cloud_user
            tags:
                    - copy_file_to_nodes

          - name: Join Cluster
            command: sh /tmp/join_command.sh
            tags:
                    - join_cluster


  handlers:
  - name : Docker status
    service: 
            name : docker
            state : started

